### ISSUE TITLE
Segmentation fault (core dumped) when using filters.python 

### ISSUE THREAD

**Issue by AlbionS** [PDAL/python#73] opened 2020-09-28 12:47 UTC
Hi,
I just found a bug using filters.python.

I have been working lately on scaling the intensity to color if a file does not have a color. Recently I found out that it does not work all the time and I kept receiving the error Segmentation fault (core dumped), at first I thought that my python script is not working correctly but that wasn't the case. Some of the files work fine and some not.

To make it easy and to prove that the error is not coming from my script so you wont have to verify it, I changed the fonction just to print something on the console : 
**rep_col.py**
```
import numpy as np
import sys
print("started")
def scale_color(ins, outs):
        print("inside")
        print("------------------Finished")
        return True
```
**pipeline.json**
```
       [
               "/home/ubuntu/Desktop/test.laz",
                {
                  "type":"filters.python",
                  "script":"/home/ubuntu/Desktop/replace_col.py",
                  "function":"scale_color",
                  "module":"anything",
                  "add_dimension":["Red=uint16","Green=uint16","Blue=uint16"]
                },
                {
                 "filename":  "/home/ubuntu/Desktop/test_.laz"
                 }
        ]
```

Link to download the files : https://gofile.io/d/0Wnhmv

Exemple of the first file, that it throws the error : 
**pdal pipeline -i /home/ubuntu/Desktop/pipeline.json**
```
started
Segmentation fault (core dumped)
```

Exemple of the second file, that it works:
**pdal pipeline -i /home/ubuntu/Desktop/pipeline.json**
```
started
inside
------------------Finished
```

I've installed pdal through conda
**pdal --version**
```
----------------------------------------------------------
pdal 2.1.0 (git-version: 1d5e8a)
----------------------------------------------------------
```

I can provide other files if needed :)
Best Regards,
Albion

**Comment by abellgithub** [comment] 2020-10-20 13:26
This is caused by an invalid string in the source metadata data not being properly handled by the library.

**Comment by abellgithub** [comment] 2020-10-20 14:50
To be more explicit, there are bytes in description of the a VLR in the source file aren't valid unicode. There is no requirement in the LAS spec that they're valid unicode, but python expects unicode strings.

**Comment by AlbionS** [comment] 2020-10-26 08:37
Thank you @abellgithub 
Will this be handled in the next version of PDAL ?

**Comment by abellgithub** [comment] 2020-10-26 12:17
It has already been released as part of the python module: https://github.com/PDAL/python/releases/tag/2.3.5

**Closed by abellgithub** 2020-10-26 12:17 UTC

**Comment by AlbionS** [comment] 2020-11-05 13:25
Thank you @abellgithub 
I never reached to install pdal through pip : ERROR: Could not build wheels for PDAL which use PEP 517 and cannot be installed directly.

I have installed it through conda, so doing "conda update pdal" of my environment will I have the bug fixed for the python filter ?
